### ISSUE TITLE
Why my drive status is always 0?

### ISSUE THREAD

**Issue by kyuhyong** [camcamfresh/Xiaomi-M365-BLE-Controller-Replacement#18]
Now I can turn on/off, lock/unlock the scooter with cloud api however I cannot actually turn on the motor.
I see serial transmission going in the TX line. 
However the DriveStatus variable always return 0 
Is there anything I can do to solve this issue?

**Comment by camcamfresh** [comment]
drive status is 0 for off, 1 for wheel movement, 2 eco on (wheel off), 3 eco on (wheel movement).

The motor will only move when drive status is 1 or 3, but a drive status of 1 or 3 doesn't necessarily mean motor is on just that the wheel is moving.

**Comment by kyuhyong** [comment]
Hi @camcamfresh Is there a way I can set the drive status other than 0?
