### ISSUE TITLE
Help Finding Connectors for Throttle and Brk

### ISSUE THREAD

**Issue by camcamfresh** [camcamfresh/Xiaomi-M365-BLE-Controller-Replacement#28]
This isn't directly code related, but I have been searching for weeks to find the same type of connectors that Xiaomi and Seagway use on their controllers with no luck.

I cannot find the 3-pin, 1.5mm female JST connector used for the brake & throttle sensors. I'm thinking I will have the same difficulty searching for the 2-pin 1.5mm female JST connector for the headlight.

![Scooter-Circuit-Board-Dashboard-Bluetooth-Board-for-Xiaomi-Mijia-Ninebot-ES1-ES2-ES3-ES4-Foldable-Electric](https://user-images.githubusercontent.com/41055736/55971246-aeb3dd00-5c46-11e9-9e92-788b3aaf2b16.jpg)

I have been able to find the male 3-pin JST connector & the cylindrical 4-pin connector, but cannot find the other connectors. Any help in finding these connectors would be appreciated.

**Comment by adezel** [comment]
@camcamfresh Where did you find those connectors? Im struggling with it (specially the cylindrical)... Thanks!

**Comment by Ursescu** [comment]
@camcamfresh Hey, can you share the name of the JST connectors ? Are those JST SH ?

**Comment by andrescli** [comment]
What is name of the 1.5mm JST throttle connector

**Comment by andrescli** [comment]
Please can anyone share the name of the 1.5mm JST throttle connector??

**Comment by mocanew** [comment]
The connectors used for throttle, brake and the led light are: JST ZHR-3, JST ZMR-03 and JST ZMR-02.
Note that these are the connectors that mate with the ones on the handlebar, aka the connectors used for the dashboard.

**Comment by Ursescu** [comment]
The cylindrical one can be found on Aliexpress under the name **Julet Connector**. The original ones I think are called Higo connectors from A&C solutions. [(Here)](https://www.higoconnector.com/products/z209bg-p-00-a0-1000/0999K#title). Also look at this #39.
