### ISSUE TITLE
How to keep particle on when we power off scooter

### ISSUE THREAD

**Issue by arminsalcin** [camcamfresh/Xiaomi-M365-BLE-Controller-Replacement#34]
Hello to all , 

So my question is when you turn off scooter by particle the 5V line is 0V so particle is off.
How can you get command from cloud to turn on scooter when 5v line is off ?

**Comment by mossafaei** [comment]
You need to use battery when scooter is off

**Comment by arminsalcin** [comment]
Thank you for answering , also question how to keep scooter always in unlocked state ?

**Comment by mossafaei** [comment]
You can use this answer: https://github.com/camcamfresh/Xiaomi-M365-BLE-Controller-Replacement/issues/19

**Comment by arminsalcin** [comment]
Thank you for answering , i already read that but what if scooter is riding and i lock and unlock it by time it will crash. It is little bit risky ...

**Comment by mossafaei** [comment]
You can get the state of the wheels and checking if scooter is riding or not

**Comment by arminsalcin** [comment]
Ok thank you for helping , i figure it out !
