### ISSUE TITLE
does this work with Ninebot ES2?

### ISSUE THREAD

**Issue by juergengunz** [camcamfresh/Xiaomi-M365-BLE-Controller-Replacement#4]
does this work with the Ninebot Segway ES2 Xiaomi Mijia Scooter too?

**Comment by camcamfresh** [comment]
I would not know, but since they use the same protocol as other Ninebot devices, I would assume so, but this is merely an assumption.

**Comment by tommydzierzak** [comment]
@juergengunz Have you had any luck with the ninebot? I have been trying myself but can't seem to get communication between the particle and the motor driver working.

**Comment by juergengunz** [comment]
@tommydzierzak Yes, but the protocol is a little bit different and as far as I know it's not public.

**Comment by geg58** [comment]
Can you push your code on github since you got it working?

**Comment by juergengunz** [comment]
@geg58 it is not allowed due to contract agreements but you can easily reverse engineer it
