### ISSUE TITLE
I can not compile. Gives an error message

### ISSUE THREAD

**Issue by VadymKC** [camcamfresh/Xiaomi-M365-BLE-Controller-Replacement#42]
firmware.ino:9:1: 'PMIC' does not name a type
firmware.ino:331:9: 'pmic' was not declared in this scope
Tell me what to do with this?

**Comment by VadymKC** [comment]
I use Photon (Device OS:1.4.4)

**Comment by camcamfresh** [comment]
I believe PMIC is only for the Electron, you might be able to use one of the pins on the photon and read the voltage level from there instead. However, you will likely need a battery. If the power turns off, then so does the Photon and you'll have no way to restart the scooter remotely.

**Comment by VadymKC** [comment]
Ok
