### ISSUE TITLE
Not really sure about what work , and don't :

### ISSUE THREAD

**Issue by sigmounte** [camcamfresh/Xiaomi-M365-BLE-Controller-Replacement#5]
So if i read well , the program is able start the skooter , read the value from accel and brake , and change the speed of the skooter ?

So normally i could make a ride with it ?

Sorry for the miss understanding :)

**Comment by camcamfresh** [comment]
Exactly! Along with the other commands like lock and unlock.

**Comment by sigmounte** [comment]
look like we don't have the same protocol , mine use FE or FF has CRC , not 2 bytes ;(
