### ISSUE TITLE
Particle Questions

### ISSUE THREAD

**Issue by jacknab** [camcamfresh/Xiaomi-M365-BLE-Controller-Replacement#8]
Hi,
I would just like to ask a few questions please.

Does your Particle board come with the GPS module from Particle or are you using a different GPS module with this project?

With your project have you updated the Particle's Device OS?  Just for helpful information could you tell me what version OS your device is working on.

The NMEAGPS library - In a previous comment you stated you use Particle IDE to compile/flash your device, I am unable to locate any library files for NMEAGPS in the IDE software, I have searched google and found the files which I manually copied into the project folder, however I still get errors when trying to compile errors stating it cant file other library files such as Arduino.h and something serial.h  And advice on what I am doing wrong would be grateful.

And my final question.. would you share your Particle APP (which gives you a link that allows others to install your built app saved on the Particle cloud server.

I am willing to donate some $ via paypal for any help... and of course for your hard work your putting into this project.

**Comment by camcamfresh** [comment]
No I am using the NEO-M8N GPS; I found it on eBay for like $20. Here's a link to one: https://www.ebay.com/itm/NEO-M8N-Big-Mini-Antenna-Flight-Controller-GPS-Module-for-PIX-APM2-56-APM2-8/202162246324?hash=item2f11cf12b4:m:mThUmVn3lJzcRX6uZlcbWIQ:rk:12:pf:0

The Device OS I have been using has been 0.7.0, but I think it will work on most of their versions. 

As for the NMEAGPS library, it is contained within the NeoGPS library. If you include that library in the side bar, you can replace the include NeoGPS library with the NMEAGPS library in your program code (which will use the library within NeoGPS). An easier way might be to 1) search for the NeoGPS library in the community libraries 2) click on it 3) scroll down to examples and select NMEAsimple.ino 4) select the "Use This Example" button 5) replace the code in the example with the code on GitHub (or your code if you have made any adjustments).

I am a little unclear about your last question: I am thinking of the iOS app that I made to control the scooter, however I am not able to share that as I had to return the Mac that I bought to create the app (I had to create the iOS app within Apple's 14 day return policy lol).  If you're asking about the code that the Electron runs on, the main code is posted on this GitHub (the version I use contains the GPS location of my home as I programmed the scooter to turn it's lights off and unlock when I arrive home).

Also, my Serial1 port broke on my Electron two days ago, so I am working with Particle to get a replacement. I may not be able to test your program for a week or two while I get a new one, though I still need to check for other Serial ports on the Electron to see if they are capable of half duplex mode.

**Comment by camcamfresh** [comment]
https://drive.google.com/file/d/1jjfAUqVoqd4QdQPzS_AQ4LxbmgaDKu9f/view?usp=sharing

**Comment by jacknab** [comment]
i did finally get it to write the firmware. question - i see the last line of code mentions gps valid = V or I, I believe this code here:  (is what you were mentioning in above comment about for your home location.

if(fix.valid.location){
                gpsUrl = "https://maps.google.com/?q=" + String(fix.latitude(), 6) + "," + String(fix.longitude(), 6);
                gpsValid = "V";
                if((String(fix.latitude()).startsWith("**.***") || String(fix.latitude()).startsWith("**.***")) && String(fix.longitude()).startsWith("-97.727")){
                    headPowerCommand = 0;
                }
                else if(lockCommand == 0){
                    ledPowerCommand = 1;
                    digitalWrite(D6, HIGH);
                }
                else{
                    ledPowerCommand = 1;
                    digitalWrite(D6, LOW);
                }
            }
            else{
                gpsValid = "I";
            }
        }


also the other files not the firmware.ino file do they need to be added when compiling the code?

**Comment by camcamfresh** [comment]
The other files are to help with troubleshooting.

**Comment by jacknab** [comment]
ah.   i finally got the firmware to write thanks to ur advice.   i see in
ur diagram u drew u changed the pins from A3 -A4  to A0 -A1  are those pins
also on a transister?   also is there a cloudcommand im suppose to call to
activate the throttle?  thats the only issue im seeming to have.


> .
>

**Comment by camcamfresh** [comment]
The switch from A3 & A4 to A0 & A1 is just for organization. They are connected to the throttle and brake sensors (blue and green wires). No transistor is used on the throttle or brake.
In order for the motor to turn on, the front wheel needs to be moving at a certain speed. I usually use the brake throttle to see if the scooter is receiving data since the brake light will always respond even if the front wheel is not moving.
