### ISSUE TITLE
bit shifting instead of strings....

### ISSUE THREAD

**Issue by smartinick** [camcamfresh/Xiaomi-M365-BLE-Controller-Replacement#9]
Not an issue, but as it seems you need to figure that out.... use it like that:

uint16_t crc = (motor1[2] + motor1[3] + motor1[4] + motor1[5] + motor1[6] + motor1[7] + motor1[8] + motor1[9] + motor1[10] + motor1[11] + motor1[12]) ^ 0xFFFF;
motor1[13] = (uint8_t)(crc&0xff);
motor1[14] = (uint8_t)((crc&0xff00)>>8);

maybe that safe you some time - your code templated saved my time (doing similar with the esp32).
Thanks for sharing!

for switching eco/normal mode you can look in my code, m365.cpp, method m365_sendcommand.

**Comment by camcamfresh** [comment]
Thank you! My friend recommended that I do this, but my microchip broke before I could test if would work. I'll try replacing my code with this when I finish making my wire harness (probably next week).

**Comment by smartinick** [comment]
you are welcome. thanks for starting this repo, saved me some time to
research myself :D
if you have any questions - ideas - i'm happy to give feedback/help!
